theme: jekyll-theme-tactile

title: Giacomo Borin
description: Mathematics is like God, perfect and infinite, with the difference that at least about God we have understood something.
author: Giacomo Borin

social-network-links:
#  email: "someone@example.com"
#  facebook: ''
  github: giacomoborin
#  twitter: ''
#  youtube: ''
#  medium: yourname
#  reddit: yourname
  linkedin: Giacomo Borin
#  xing: yourname
#  stackoverflow: ""
#  snapchat: ''
#  instagram: ''
#  spotify: yourname
#  telephone: ''
#  steam: ''
#  twitch: ''
#  yelp: yourname
  telegram: giacomoborin
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar



github:
  is_project_page: false
markdown: kramdown
kramdown:
    math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
